### PR TITLE
add CouchDB Logo, brand book

### PR DESCRIPTION
**Pull request by cmnstmntmn**

### CODE REVIEW

**Comment by kxepal** [comment]
Nice! cc @janl @robertkowalski @michellephung

**Comment by michellephung** [comment]
+1 Very cool!! Thanks @cmnstmntmn

**Comment by kxepal** [comment]
+1 @cmnstmntmn please merge!

**Comment by janl** [comment]
Merged, thank you so much! <3

**Comment by cmnstmntmn** [comment]
my pleasure (;

**Pull request merged**
