### PR TITLE
Strengthen requirements on backwards-incompatible API changes; clarify vetoes

### PR DESCRIPTION
**Pull request by wohali**
A recent incident in the project over confusion about HTTP API endpoint changes made it clear that our bylaws can be strengthened in this area.

This change proposes a mandatory developer mailing list notification and at least a Lazy Consensus decision whenever a backwards-incompatible change is made to a release branch, or to `master`.

It also takes the step that changes to `master` constitute a **technical decision** of the project, since our intention is that `master` is always releasable, and quite often new minor releases of CouchDB are forked from `master`, not the previous major or minor release branch.

### CODE REVIEW

**Comment by wohali** [comment]
This change requires a Lazy 2/3 Majority vote on the developer mailing list; that vote has been started at 05:25 2018.02.08.

**Review by kxepal — APPROVED** [review]
+1

**Comment by janl** [comment]
+1 (mirror of my mailing list vote)

**Comment by wohali** [comment]
I have made minor modifications:

* Preserve backwards compatibility only for endpoints in released CouchDB versions
* Don't promise backwards compatibility for bugs or for undocumented functionality (e.g., sequence number format 1.x -> 2.x)

**Comment by davisp** [comment]
+1

**Comment by rnewson** [comment]
+1

**Pull request merged**
